apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp1
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
      - name: testapp1
        image: sokoide/testapp1:latest
        ports:
        - containerPort: 10001
        env:
        - name: PORT
          value: "10001"

---
apiVersion: v1
kind: Service
metadata:
  name: testapp1-svc
spec:
  selector:
    app: testapp1
  ports:
  - protocol: TCP
    port: 10001
  type: NodePort
